### ISSUE TITLE
Re: Make it work in Firefox

### ISSUE THREAD

**Issue by svendahlstrand** [robinsloan/perfect-edition#1]
Hello Robin,

The book works reasonably well for me in Firefox 78.0.1. But there's a line of code that Firefox will choke on:

https://github.com/robinsloan/perfect-edition/blob/474885e698221344d9b2655cbd49384cf6e81750/source/_web-template/web-template.html#L182

`Element.scrollIntoViewIfNeeded()` is [not supported in Firefox yet](https://caniuse.com/#feat=scrollintoviewifneeded). You could use `Element.scrollIntoView()` instead.

I'm so happy the Sloanstarter worked out, looking forward to this new Annabel adventure.

**Comment by robinsloan** [comment]
I just updated my Firefox and I'm now wondering exactly *how* old & crusty the version I had was… because yes, now it looks pretty good. (Previously, it was illegible & unnavigable.) Okay, this todo will be easier than I thought…!
