### ISSUE TITLE
Remove Firefox warning 

### ISSUE THREAD

**Issue by mattkatz** [robinsloan/perfect-edition#12]
Firefox works on this!

**Comment by mattkatz** [comment]
Just to be clear - I'm referring to the published version on robinsloan.com - I think you just need to do a build and push - I looked but it seems like the warning is gone from this code, otherwise this would be a pull request

**Comment by robinsloan** [comment]
Oof, thank you for mentioning this! Fixed now. As I mentioned elsewhere, I was, mortifyingly, using a really very old version of Firefox which is what made me believe it was so broken.

Thanks again!
