### ISSUE TITLE
Maximize screen space

### ISSUE THREAD

**Issue by joelcardinal** [robinsloan/perfect-edition#13]
Move the table of contents button to a small hamburger in the corner and place more text on screen with that gained vertical space -- this goes for all devices.  Reduce your side margins on mobile.  On Desktop, I'd suggest removing the previous and next page, it visually detracts from reading the central content.

**Comment by robinsloan** [comment]
Thanks for the ideas! I like the adjacent pages in the desktop/laptop view; I do think the specific value of the fade etc. could use some tinkering, though.

The menu placement merits experimentation for sure.

Thanks again!
