### ISSUE TITLE
Firefox desktop, no navigation

### ISSUE THREAD

**Issue by pmontrasio** [robinsloan/perfect-edition#18]
I went to https://robinsloan.github.io/perfect-edition/build/web/index.html# with Firefox 78.0.1 (Ubuntu 20.04). I tried to navigate with any of

> On a laptop: Use the arrow keys, the space bar, or the touch pad
> On a desktop: Use any of the above, or the scroll wheel

but I'm stuck on the first page.

Vivaldi and Chrome work. Firefox 68 on Android 10 works too.

I traced the events up to into `smoothScrollStep`. At the line

```
if (Math.abs(currentX - context.x) > 2.0) {
```

`currentX` is 0 and `context.x` is 668. This leads into the `else` branch which is empty. This seems different than issue #1

**Comment by robinsloan** [comment]
Hmm, this is a good bug report---thank you. I'll investigate.

**Comment by todrobbins** [comment]
Just tested with Firefox 79.0 on macOS 10.15.6 and keyboard shortcuts are working fine.
