### ISSUE TITLE
Missing directories when running for the first time

### ISSUE THREAD

**Issue by svendahlstrand** [robinsloan/perfect-edition#2]
When cloning the project for the first time and running `ruby serve.rb` the following error message manifested itself before my eyes:

```bash
Traceback (most recent call last):
	1: from generate.rb:133:in `<main>'
generate.rb:133:in `write': No such file or directory @ rb_sysopen - build/annabel-scheme-new-golden-gate/web/web-book.html (Errno::ENOENT)
```

Luckily it's easy enough to work around by creating the missing directories:

```bash
mkdir -p build/annabel-scheme-new-golden-gate/web
```
The build script could make sure the directories exist using [`FileUtils.mkdir_p(list, **options)`](https://ruby-doc.org/stdlib-2.7.1/libdoc/fileutils/rdoc/FileUtils.html#method-c-mkdir_p).

**Comment by robinsloan** [comment]
This is exactly the kind of thing you don't notice until someone else tries to run the project. Fixed!
