### ISSUE TITLE
Generate.rb is aborting

### ISSUE THREAD

**Issue by okpatil4u** [robinsloan/perfect-edition#22]
Thank you for this great project.

I haven't been able to make it work. 
1. I have mac os x catalina. I cloned the repo.
2. Ran bundle install and ruby serve.rb
3. When I tried to visit http://localhost:8000/
```
[2020-07-29 16:33:30] INFO  WEBrick 1.4.2
[2020-07-29 16:33:30] INFO  ruby 2.6.3 (2019-04-16) [universal.x86_64-darwin19]
[2020-07-29 16:33:30] INFO  WEBrick::HTTPServer#start: pid=20159 port=8000
[2020-07-29 16:33:38] ERROR `/' not found.
```
This was the error. When I tried to run ruby generate.rb, it showed me this
`[1]    21068 abort      ruby generate.rb`

I am not sure what I am doing wrong. Please help me out.

**Comment by robinsloan** [comment]
What output do you get when you run `ruby generate.rb` directly, rather than `ruby serve.rb`?

**Comment by robinsloan** [comment]
I did find this (by googling "macos catalina ruby abort") which might be useful:

https://gist.github.com/ritaly/9ded38e1918e55b928ff357fbdf07417

**Comment by okpatil4u** [comment]
Thanks. I am following on the link you sent. The code is failing at  `require "nokogiri"` in generate.rb

**Comment by robinsloan** [comment]
Hmm, okay. My spidey sense is telling me the problem has to do with OpenSSL, which Nokogiri uses. Just a thought.

Here's something that might be worth investigating: https://stackoverflow.com/questions/37336573/unable-to-require-openssl-install-openssl-and-rebuild-ruby-preferred-or-use-n/42235933

**Comment by okpatil4u** [comment]
This seems to be an OS specific issue. Thank you very much for your help.
