### ISSUE TITLE
Font rendering broken in Firefox 78

### ISSUE THREAD

**Issue by heyarne** [robinsloan/perfect-edition#23]
Hi! I really like the template. Unfortunately the text looks a bit garbled in my browser.

Here is a screenshot of the template, note especially the letters "p", "b" and "m":
![image](https://user-images.githubusercontent.com/525780/88795496-67858e80-d1a0-11ea-8e5c-8602854bc624.png)

Here is a screenshot of the Vollkorn website for comparison, which loooks crisp:
![image](https://user-images.githubusercontent.com/525780/88795606-98fe5a00-d1a0-11ea-8b0c-ff9e3d8aaa4c.png)

The problem seems to be fixed by increasing the font size on `body` to at least `1.1rem`:
![image](https://user-images.githubusercontent.com/525780/88795744-cfd47000-d1a0-11ea-9d89-1407ed37dc43.png)

**Comment by robinsloan** [comment]
Thanks for this investigation---what an odd glitch. I could imagine just setting a minimum font size of `1.1rem` (which I think would work fine, even for people who like to read "small" text). What do you think?

**Comment by heyarne** [comment]
I can't really explain it either. Firefox on Android works fine. I think that setting the minimum font size to `1.1rem` is a good solution.
