### ISSUE TITLE
Changing spot colour

### ISSUE THREAD

**Issue by nmifsud** [robinsloan/perfect-edition#30]
Not sure if this is a bug or a feature suggestion: it'd be nice if the build web CSS reflected the `spot_color` specified in `book.yaml`. I had to manually change `--spot-color` and `--selection-color`.

**Comment by robinsloan** [comment]
Nathan, this (and your other notes) are great! Thank you!

Edits / pull requests are warmly invited. Otherwise, I'll go down the list as time permits. Thanks again!
