### ISSUE TITLE
trackpad scrolling to the end of content keeps scrolling multiple more pages

### ISSUE THREAD

**Issue by camilokoch** [robinsloan/perfect-edition#35]
the mobile experience presents the same issue as trackpad scrolling. utilizing the arrow keys does not add multiple pages at the end of the content

**Comment by robinsloan** [comment]
Hello! I don't really understand this issue; can you describe it with more detail?

**Comment by robinsloan** [comment]
Update: okay, I've figured out what you're referring to; sorry to be dense. Thanks for the observation & the report.

Unfortunately, I'm not sure how to fix this. Suggestions welcome!

**Comment by camilokoch** [comment]
thanks, robin. the last generated page should be the one with the last bit, but some empty pages are generated at the end of the web e-book as shown in the attachment. i couldn't figure out the reason
![perfect-edition](https://user-images.githubusercontent.com/62797279/95875638-ce304680-0da4-11eb-8946-1a519d673cc5.gif)

**Comment by robinsloan** [comment]
I think this works a bit better now!
